// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	params "gopherbin/params"

	mock "github.com/stretchr/testify/mock"
)

// MockUserManager is an autogenerated mock type for the UserManager type
type MockUserManager struct {
	mock.Mock
}

type MockUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManager) EXPECT() *MockUserManager_Expecter {
	return &MockUserManager_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, info
func (_m *MockUserManager) Authenticate(ctx context.Context, info params.PasswordLoginParams) (context.Context, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, params.PasswordLoginParams) (context.Context, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, params.PasswordLoginParams) context.Context); ok {
		r0 = rf(ctx, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, params.PasswordLoginParams) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUserManager_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - info params.PasswordLoginParams
func (_e *MockUserManager_Expecter) Authenticate(ctx interface{}, info interface{}) *MockUserManager_Authenticate_Call {
	return &MockUserManager_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, info)}
}

func (_c *MockUserManager_Authenticate_Call) Run(run func(ctx context.Context, info params.PasswordLoginParams)) *MockUserManager_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(params.PasswordLoginParams))
	})
	return _c
}

func (_c *MockUserManager_Authenticate_Call) Return(_a0 context.Context, _a1 error) *MockUserManager_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_Authenticate_Call) RunAndReturn(run func(context.Context, params.PasswordLoginParams) (context.Context, error)) *MockUserManager_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// BlacklistToken provides a mock function with given fields: tokenID, expiration
func (_m *MockUserManager) BlacklistToken(tokenID string, expiration int64) error {
	ret := _m.Called(tokenID, expiration)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(tokenID, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_BlacklistToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistToken'
type MockUserManager_BlacklistToken_Call struct {
	*mock.Call
}

// BlacklistToken is a helper method to define mock.On call
//   - tokenID string
//   - expiration int64
func (_e *MockUserManager_Expecter) BlacklistToken(tokenID interface{}, expiration interface{}) *MockUserManager_BlacklistToken_Call {
	return &MockUserManager_BlacklistToken_Call{Call: _e.mock.On("BlacklistToken", tokenID, expiration)}
}

func (_c *MockUserManager_BlacklistToken_Call) Run(run func(tokenID string, expiration int64)) *MockUserManager_BlacklistToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MockUserManager_BlacklistToken_Call) Return(_a0 error) *MockUserManager_BlacklistToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_BlacklistToken_Call) RunAndReturn(run func(string, int64) error) *MockUserManager_BlacklistToken_Call {
	_c.Call.Return(run)
	return _c
}

// CleanTokens provides a mock function with no fields
func (_m *MockUserManager) CleanTokens() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_CleanTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanTokens'
type MockUserManager_CleanTokens_Call struct {
	*mock.Call
}

// CleanTokens is a helper method to define mock.On call
func (_e *MockUserManager_Expecter) CleanTokens() *MockUserManager_CleanTokens_Call {
	return &MockUserManager_CleanTokens_Call{Call: _e.mock.On("CleanTokens")}
}

func (_c *MockUserManager_CleanTokens_Call) Run(run func()) *MockUserManager_CleanTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserManager_CleanTokens_Call) Return(_a0 error) *MockUserManager_CleanTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_CleanTokens_Call) RunAndReturn(run func() error) *MockUserManager_CleanTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserManager) Create(ctx context.Context, user params.NewUserParams) (params.Users, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 params.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, params.NewUserParams) (params.Users, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, params.NewUserParams) params.Users); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(params.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, params.NewUserParams) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user params.NewUserParams
func (_e *MockUserManager_Expecter) Create(ctx interface{}, user interface{}) *MockUserManager_Create_Call {
	return &MockUserManager_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserManager_Create_Call) Run(run func(ctx context.Context, user params.NewUserParams)) *MockUserManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(params.NewUserParams))
	})
	return _c
}

func (_c *MockUserManager_Create_Call) Return(_a0 params.Users, _a1 error) *MockUserManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_Create_Call) RunAndReturn(run func(context.Context, params.NewUserParams) (params.Users, error)) *MockUserManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSuperUser provides a mock function with given fields: user
func (_m *MockUserManager) CreateSuperUser(user params.NewUserParams) (params.Users, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateSuperUser")
	}

	var r0 params.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(params.NewUserParams) (params.Users, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(params.NewUserParams) params.Users); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(params.Users)
	}

	if rf, ok := ret.Get(1).(func(params.NewUserParams) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_CreateSuperUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuperUser'
type MockUserManager_CreateSuperUser_Call struct {
	*mock.Call
}

// CreateSuperUser is a helper method to define mock.On call
//   - user params.NewUserParams
func (_e *MockUserManager_Expecter) CreateSuperUser(user interface{}) *MockUserManager_CreateSuperUser_Call {
	return &MockUserManager_CreateSuperUser_Call{Call: _e.mock.On("CreateSuperUser", user)}
}

func (_c *MockUserManager_CreateSuperUser_Call) Run(run func(user params.NewUserParams)) *MockUserManager_CreateSuperUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(params.NewUserParams))
	})
	return _c
}

func (_c *MockUserManager_CreateSuperUser_Call) Return(_a0 params.Users, _a1 error) *MockUserManager_CreateSuperUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_CreateSuperUser_Call) RunAndReturn(run func(params.NewUserParams) (params.Users, error)) *MockUserManager_CreateSuperUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *MockUserManager) Delete(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserManager_Expecter) Delete(ctx interface{}, userID interface{}) *MockUserManager_Delete_Call {
	return &MockUserManager_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockUserManager_Delete_Call) Run(run func(ctx context.Context, userID uint)) *MockUserManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserManager_Delete_Call) Return(_a0 error) *MockUserManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockUserManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Disable provides a mock function with given fields: ctx, userID
func (_m *MockUserManager) Disable(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockUserManager_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserManager_Expecter) Disable(ctx interface{}, userID interface{}) *MockUserManager_Disable_Call {
	return &MockUserManager_Disable_Call{Call: _e.mock.On("Disable", ctx, userID)}
}

func (_c *MockUserManager_Disable_Call) Run(run func(ctx context.Context, userID uint)) *MockUserManager_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserManager_Disable_Call) Return(_a0 error) *MockUserManager_Disable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_Disable_Call) RunAndReturn(run func(context.Context, uint) error) *MockUserManager_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// Enable provides a mock function with given fields: ctx, userID
func (_m *MockUserManager) Enable(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Enable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockUserManager_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserManager_Expecter) Enable(ctx interface{}, userID interface{}) *MockUserManager_Enable_Call {
	return &MockUserManager_Enable_Call{Call: _e.mock.On("Enable", ctx, userID)}
}

func (_c *MockUserManager_Enable_Call) Run(run func(ctx context.Context, userID uint)) *MockUserManager_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserManager_Enable_Call) Return(_a0 error) *MockUserManager_Enable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_Enable_Call) RunAndReturn(run func(context.Context, uint) error) *MockUserManager_Enable_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID
func (_m *MockUserManager) Get(ctx context.Context, userID uint) (params.Users, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 params.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (params.Users, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) params.Users); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(params.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserManager_Expecter) Get(ctx interface{}, userID interface{}) *MockUserManager_Get_Call {
	return &MockUserManager_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *MockUserManager_Get_Call) Run(run func(ctx context.Context, userID uint)) *MockUserManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserManager_Get_Call) Return(_a0 params.Users, _a1 error) *MockUserManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_Get_Call) RunAndReturn(run func(context.Context, uint) (params.Users, error)) *MockUserManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HasSuperUser provides a mock function with no fields
func (_m *MockUserManager) HasSuperUser() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasSuperUser")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockUserManager_HasSuperUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSuperUser'
type MockUserManager_HasSuperUser_Call struct {
	*mock.Call
}

// HasSuperUser is a helper method to define mock.On call
func (_e *MockUserManager_Expecter) HasSuperUser() *MockUserManager_HasSuperUser_Call {
	return &MockUserManager_HasSuperUser_Call{Call: _e.mock.On("HasSuperUser")}
}

func (_c *MockUserManager_HasSuperUser_Call) Run(run func()) *MockUserManager_HasSuperUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserManager_HasSuperUser_Call) Return(_a0 bool) *MockUserManager_HasSuperUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_HasSuperUser_Call) RunAndReturn(run func() bool) *MockUserManager_HasSuperUser_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, results
func (_m *MockUserManager) List(ctx context.Context, page int64, results int64) (params.UserListResult, error) {
	ret := _m.Called(ctx, page, results)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 params.UserListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (params.UserListResult, error)); ok {
		return rf(ctx, page, results)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) params.UserListResult); ok {
		r0 = rf(ctx, page, results)
	} else {
		r0 = ret.Get(0).(params.UserListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, page, results)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - results int64
func (_e *MockUserManager_Expecter) List(ctx interface{}, page interface{}, results interface{}) *MockUserManager_List_Call {
	return &MockUserManager_List_Call{Call: _e.mock.On("List", ctx, page, results)}
}

func (_c *MockUserManager_List_Call) Run(run func(ctx context.Context, page int64, results int64)) *MockUserManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockUserManager_List_Call) Return(paste params.UserListResult, err error) *MockUserManager_List_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockUserManager_List_Call) RunAndReturn(run func(context.Context, int64, int64) (params.UserListResult, error)) *MockUserManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, update
func (_m *MockUserManager) Update(ctx context.Context, userID uint, update params.UpdateUserPayload) (params.Users, error) {
	ret := _m.Called(ctx, userID, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 params.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, params.UpdateUserPayload) (params.Users, error)); ok {
		return rf(ctx, userID, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, params.UpdateUserPayload) params.Users); ok {
		r0 = rf(ctx, userID, update)
	} else {
		r0 = ret.Get(0).(params.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, params.UpdateUserPayload) error); ok {
		r1 = rf(ctx, userID, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - update params.UpdateUserPayload
func (_e *MockUserManager_Expecter) Update(ctx interface{}, userID interface{}, update interface{}) *MockUserManager_Update_Call {
	return &MockUserManager_Update_Call{Call: _e.mock.On("Update", ctx, userID, update)}
}

func (_c *MockUserManager_Update_Call) Run(run func(ctx context.Context, userID uint, update params.UpdateUserPayload)) *MockUserManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(params.UpdateUserPayload))
	})
	return _c
}

func (_c *MockUserManager_Update_Call) Return(_a0 params.Users, _a1 error) *MockUserManager_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_Update_Call) RunAndReturn(run func(context.Context, uint, params.UpdateUserPayload) (params.Users, error)) *MockUserManager_Update_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenID
func (_m *MockUserManager) ValidateToken(tokenID string) error {
	ret := _m.Called(tokenID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManager_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockUserManager_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenID string
func (_e *MockUserManager_Expecter) ValidateToken(tokenID interface{}) *MockUserManager_ValidateToken_Call {
	return &MockUserManager_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenID)}
}

func (_c *MockUserManager_ValidateToken_Call) Run(run func(tokenID string)) *MockUserManager_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserManager_ValidateToken_Call) Return(_a0 error) *MockUserManager_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManager_ValidateToken_Call) RunAndReturn(run func(string) error) *MockUserManager_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManager creates a new instance of MockUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManager {
	mock := &MockUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
