// Copyright 2019 Gabriel-Adrian Samfira
//
//    Licensed under the Apache License, Version 2.0 (the "License"); you may
//    not use this file except in compliance with the License. You may obtain
//    a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
//    License for the specific language governing permissions and limitations
//    under the License.

package controllers

// LanguageMappings is a list of language to class mapping
// that works with highlightjs
var LanguageMappings = map[string]string{
	"Django":                  "django",
	"Dockerfile":              "dockerfile",
	"dsconfig":                "dsconfig",
	"DTS (Device Tree)":       "dts",
	"Dust":                    "dust",
	"EBNF":                    "ebnf",
	"Elixir":                  "elixir",
	"Elm":                     "elm",
	"Erlang":                  "erlang",
	"Excel":                   "excel",
	"F#":                      "fsharp",
	"FIX":                     "fix",
	"Fortran":                 "fortran",
	"G-Code":                  "gcode",
	"Gams":                    "gams",
	"GAUSS":                   "gauss",
	"Gherkin":                 "gherkin",
	"Go":                      "go",
	"Golo":                    "golo",
	"Gradle":                  "gradle",
	"Groovy":                  "groovy",
	"HTML":                    "html",
	"HTTP":                    "http",
	"Haml":                    "haml",
	"Handlebars":              "handlebars",
	"Haskell":                 "haskell",
	"Haxe":                    "haxe",
	"Hy":                      "hy",
	"Ini":                     "ini",
	"Inform7":                 "inform7",
	"IRPF90":                  "irpf90",
	"JSON":                    "json",
	"Java":                    "java",
	"JavaScript":              "javascript",
	"Kotlin":                  "kotlin",
	"Leaf":                    "leaf",
	"Lasso":                   "lasso",
	"Less":                    "less",
	"LDIF":                    "ldif",
	"Lisp":                    "lisp",
	"LiveCode Server":         "livecodeserver",
	"LiveScript":              "livescript",
	"Lua":                     "lua",
	"Makefile":                "makefile",
	"Markdown":                "markdown",
	"Mathematica":             "mathematica",
	"Matlab":                  "matlab",
	"Maxima":                  "maxima",
	"Maya Embedded Language":  "mel",
	"Mercury":                 "mercury",
	"Mizar":                   "mizar",
	"Mojolicious":             "mojolicious",
	"Monkey":                  "monkey",
	"Moonscript":              "moonscript",
	"N1QL":                    "n1ql",
	"NSIS":                    "nsis",
	"Nginx":                   "nginx",
	"Nimrod":                  "nimrod",
	"Nix":                     "nix",
	"OCaml":                   "ocaml",
	"Objective C":             "objectivec",
	"OpenGL Shading Language": "glsl",
	"OpenSCAD":                "openscad",
	"Oracle Rules Language":   "ruleslanguage",
	"Oxygene":                 "oxygene",
	"PF":                      "pf",
	"PHP":                     "php",
	"Parser3":                 "parser3",
	"Perl":                    "perl",
	"Plaintext":               "plaintext",
	"Pony":                    "pony",
	"PostgreSQL & PL/pgSQL":   "pgsql",
	"PowerShell":              "powershell",
	"Processing":              "processing",
	"Prolog":                  "prolog",
	"Properties":              "properties",
	"Protocol Buffers":        "protobuf",
	"Puppet":                  "puppet",
	"Python":                  "python",
	"Python profiler results": "profile",
	"Q":                       "k",
	"QML":                     "qml",
	"R":                       "r",
	"ReasonML":                "reasonml",
	"RenderMan RIB":           "rib",
	"RenderMan RSL":           "rsl",
	"Roboconf":                "graph",
	"Ruby":                    "ruby",
	"Rust":                    "rust",
	"SAS":                     "SAS",
	"SCSS":                    "scss",
	"SQL":                     "sql",
	"STEP Part 21":            "p21",
	"Scala":                   "scala",
	"Scheme":                  "scheme",
	"Scilab":                  "scilab",
	"Shell":                   "shell",
	"Smali":                   "smali",
	"Smalltalk":               "smalltalk",
	"Stan":                    "stan",
	"Stata":                   "stata",
	"Stylus":                  "stylus",
	"SubUnit":                 "subunit",
	"Swift":                   "swift",
	"Tcl":                     "tcl",
	"Test Anything Protocol":  "tap",
	"TeX":                     "tex",
	"Thrift":                  "thrift",
	"TP":                      "tp",
	"Twig":                    "twig",
	"TypeScript":              "typescript",
	"VB.Net":                  "vbnet",
	"VBScript":                "vbscript",
	"VHDL":                    "vhdl",
	"Vala":                    "vala",
	"Verilog":                 "verilog",
	"Vim Script":              "vim",
	"x86 Assembly":            "x86asm",
	"XL":                      "xl",
	"XQuery":                  "xquery",
	"YAML":                    "yml",
	"Zephir":                  "zephir",
}

func hasLanguage(lang string) bool {
	for _, val := range LanguageMappings {
		if val == lang {
			return true
		}
	}
	return false
}
