// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	params "gopherbin/params"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamManager is an autogenerated mock type for the TeamManager type
type MockTeamManager struct {
	mock.Mock
}

type MockTeamManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamManager) EXPECT() *MockTeamManager_Expecter {
	return &MockTeamManager_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, team, member
func (_m *MockTeamManager) AddMember(ctx context.Context, team string, member string) (params.TeamMember, error) {
	ret := _m.Called(ctx, team, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 params.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (params.TeamMember, error)); ok {
		return rf(ctx, team, member)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) params.TeamMember); ok {
		r0 = rf(ctx, team, member)
	} else {
		r0 = ret.Get(0).(params.TeamMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, team, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamManager_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTeamManager_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
//   - member string
func (_e *MockTeamManager_Expecter) AddMember(ctx interface{}, team interface{}, member interface{}) *MockTeamManager_AddMember_Call {
	return &MockTeamManager_AddMember_Call{Call: _e.mock.On("AddMember", ctx, team, member)}
}

func (_c *MockTeamManager_AddMember_Call) Run(run func(ctx context.Context, team string, member string)) *MockTeamManager_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTeamManager_AddMember_Call) Return(_a0 params.TeamMember, _a1 error) *MockTeamManager_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamManager_AddMember_Call) RunAndReturn(run func(context.Context, string, string) (params.TeamMember, error)) *MockTeamManager_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, name
func (_m *MockTeamManager) Create(ctx context.Context, name string) (params.Teams, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 params.Teams
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (params.Teams, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) params.Teams); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(params.Teams)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamManager_Expecter) Create(ctx interface{}, name interface{}) *MockTeamManager_Create_Call {
	return &MockTeamManager_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockTeamManager_Create_Call) Run(run func(ctx context.Context, name string)) *MockTeamManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamManager_Create_Call) Return(team params.Teams, err error) *MockTeamManager_Create_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamManager_Create_Call) RunAndReturn(run func(context.Context, string) (params.Teams, error)) *MockTeamManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name
func (_m *MockTeamManager) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamManager_Expecter) Delete(ctx interface{}, name interface{}) *MockTeamManager_Delete_Call {
	return &MockTeamManager_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockTeamManager_Delete_Call) Run(run func(ctx context.Context, name string)) *MockTeamManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamManager_Delete_Call) Return(_a0 error) *MockTeamManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamManager_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTeamManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name
func (_m *MockTeamManager) Get(ctx context.Context, name string) (params.Teams, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 params.Teams
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (params.Teams, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) params.Teams); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(params.Teams)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTeamManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamManager_Expecter) Get(ctx interface{}, name interface{}) *MockTeamManager_Get_Call {
	return &MockTeamManager_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockTeamManager_Get_Call) Run(run func(ctx context.Context, name string)) *MockTeamManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamManager_Get_Call) Return(team params.Teams, err error) *MockTeamManager_Get_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamManager_Get_Call) RunAndReturn(run func(context.Context, string) (params.Teams, error)) *MockTeamManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, results
func (_m *MockTeamManager) List(ctx context.Context, page int64, results int64) (params.TeamListResult, error) {
	ret := _m.Called(ctx, page, results)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 params.TeamListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (params.TeamListResult, error)); ok {
		return rf(ctx, page, results)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) params.TeamListResult); ok {
		r0 = rf(ctx, page, results)
	} else {
		r0 = ret.Get(0).(params.TeamListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, page, results)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTeamManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - results int64
func (_e *MockTeamManager_Expecter) List(ctx interface{}, page interface{}, results interface{}) *MockTeamManager_List_Call {
	return &MockTeamManager_List_Call{Call: _e.mock.On("List", ctx, page, results)}
}

func (_c *MockTeamManager_List_Call) Run(run func(ctx context.Context, page int64, results int64)) *MockTeamManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockTeamManager_List_Call) Return(teams params.TeamListResult, err error) *MockTeamManager_List_Call {
	_c.Call.Return(teams, err)
	return _c
}

func (_c *MockTeamManager_List_Call) RunAndReturn(run func(context.Context, int64, int64) (params.TeamListResult, error)) *MockTeamManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, team
func (_m *MockTeamManager) ListMembers(ctx context.Context, team string) ([]params.TeamMember, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []params.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]params.TeamMember, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []params.TeamMember); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]params.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamManager_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockTeamManager_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
func (_e *MockTeamManager_Expecter) ListMembers(ctx interface{}, team interface{}) *MockTeamManager_ListMembers_Call {
	return &MockTeamManager_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, team)}
}

func (_c *MockTeamManager_ListMembers_Call) Run(run func(ctx context.Context, team string)) *MockTeamManager_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamManager_ListMembers_Call) Return(_a0 []params.TeamMember, _a1 error) *MockTeamManager_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamManager_ListMembers_Call) RunAndReturn(run func(context.Context, string) ([]params.TeamMember, error)) *MockTeamManager_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, team, member
func (_m *MockTeamManager) RemoveMember(ctx context.Context, team string, member string) error {
	ret := _m.Called(ctx, team, member)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, team, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamManager_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockTeamManager_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
//   - member string
func (_e *MockTeamManager_Expecter) RemoveMember(ctx interface{}, team interface{}, member interface{}) *MockTeamManager_RemoveMember_Call {
	return &MockTeamManager_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, team, member)}
}

func (_c *MockTeamManager_RemoveMember_Call) Run(run func(ctx context.Context, team string, member string)) *MockTeamManager_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTeamManager_RemoveMember_Call) Return(_a0 error) *MockTeamManager_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamManager_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTeamManager_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamManager creates a new instance of MockTeamManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamManager {
	mock := &MockTeamManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
