// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	params "gopherbin/params"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPaster is an autogenerated mock type for the Paster type
type MockPaster struct {
	mock.Mock
}

type MockPaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaster) EXPECT() *MockPaster_Expecter {
	return &MockPaster_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata
func (_m *MockPaster) Create(ctx context.Context, data []byte, title string, language string, description string, expires *time.Time, isPublic bool, team string, selfDestructAfterViews *int, metadata map[string]string) (params.Paste, error) {
	ret := _m.Called(ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 params.Paste
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, *time.Time, bool, string, *int, map[string]string) (params.Paste, error)); ok {
		return rf(ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, *time.Time, bool, string, *int, map[string]string) params.Paste); ok {
		r0 = rf(ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata)
	} else {
		r0 = ret.Get(0).(params.Paste)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string, string, *time.Time, bool, string, *int, map[string]string) error); ok {
		r1 = rf(ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaster_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - title string
//   - language string
//   - description string
//   - expires *time.Time
//   - isPublic bool
//   - team string
//   - selfDestructAfterViews *int
//   - metadata map[string]string
func (_e *MockPaster_Expecter) Create(ctx interface{}, data interface{}, title interface{}, language interface{}, description interface{}, expires interface{}, isPublic interface{}, team interface{}, selfDestructAfterViews interface{}, metadata interface{}) *MockPaster_Create_Call {
	return &MockPaster_Create_Call{Call: _e.mock.On("Create", ctx, data, title, language, description, expires, isPublic, team, selfDestructAfterViews, metadata)}
}

func (_c *MockPaster_Create_Call) Run(run func(ctx context.Context, data []byte, title string, language string, description string, expires *time.Time, isPublic bool, team string, selfDestructAfterViews *int, metadata map[string]string)) *MockPaster_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(string), args[4].(string), args[5].(*time.Time), args[6].(bool), args[7].(string), args[8].(*int), args[9].(map[string]string))
	})
	return _c
}

func (_c *MockPaster_Create_Call) Return(paste params.Paste, err error) *MockPaster_Create_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockPaster_Create_Call) RunAndReturn(run func(context.Context, []byte, string, string, string, *time.Time, bool, string, *int, map[string]string) (params.Paste, error)) *MockPaster_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, pasteID
func (_m *MockPaster) Delete(ctx context.Context, pasteID string) error {
	ret := _m.Called(ctx, pasteID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pasteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaster_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPaster_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
func (_e *MockPaster_Expecter) Delete(ctx interface{}, pasteID interface{}) *MockPaster_Delete_Call {
	return &MockPaster_Delete_Call{Call: _e.mock.On("Delete", ctx, pasteID)}
}

func (_c *MockPaster_Delete_Call) Run(run func(ctx context.Context, pasteID string)) *MockPaster_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaster_Delete_Call) Return(_a0 error) *MockPaster_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaster_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPaster_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, pasteID
func (_m *MockPaster) Get(ctx context.Context, pasteID string) (params.Paste, error) {
	ret := _m.Called(ctx, pasteID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 params.Paste
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (params.Paste, error)); ok {
		return rf(ctx, pasteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) params.Paste); ok {
		r0 = rf(ctx, pasteID)
	} else {
		r0 = ret.Get(0).(params.Paste)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pasteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPaster_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
func (_e *MockPaster_Expecter) Get(ctx interface{}, pasteID interface{}) *MockPaster_Get_Call {
	return &MockPaster_Get_Call{Call: _e.mock.On("Get", ctx, pasteID)}
}

func (_c *MockPaster_Get_Call) Run(run func(ctx context.Context, pasteID string)) *MockPaster_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaster_Get_Call) Return(paste params.Paste, err error) *MockPaster_Get_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockPaster_Get_Call) RunAndReturn(run func(context.Context, string) (params.Paste, error)) *MockPaster_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicPaste provides a mock function with given fields: ctx, pasteID
func (_m *MockPaster) GetPublicPaste(ctx context.Context, pasteID string) (params.Paste, error) {
	ret := _m.Called(ctx, pasteID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicPaste")
	}

	var r0 params.Paste
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (params.Paste, error)); ok {
		return rf(ctx, pasteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) params.Paste); ok {
		r0 = rf(ctx, pasteID)
	} else {
		r0 = ret.Get(0).(params.Paste)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pasteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_GetPublicPaste_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicPaste'
type MockPaster_GetPublicPaste_Call struct {
	*mock.Call
}

// GetPublicPaste is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
func (_e *MockPaster_Expecter) GetPublicPaste(ctx interface{}, pasteID interface{}) *MockPaster_GetPublicPaste_Call {
	return &MockPaster_GetPublicPaste_Call{Call: _e.mock.On("GetPublicPaste", ctx, pasteID)}
}

func (_c *MockPaster_GetPublicPaste_Call) Run(run func(ctx context.Context, pasteID string)) *MockPaster_GetPublicPaste_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaster_GetPublicPaste_Call) Return(paste params.Paste, err error) *MockPaster_GetPublicPaste_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockPaster_GetPublicPaste_Call) RunAndReturn(run func(context.Context, string) (params.Paste, error)) *MockPaster_GetPublicPaste_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, results
func (_m *MockPaster) List(ctx context.Context, page int64, results int64) (params.PasteListResult, error) {
	ret := _m.Called(ctx, page, results)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 params.PasteListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (params.PasteListResult, error)); ok {
		return rf(ctx, page, results)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) params.PasteListResult); ok {
		r0 = rf(ctx, page, results)
	} else {
		r0 = ret.Get(0).(params.PasteListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, page, results)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPaster_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int64
//   - results int64
func (_e *MockPaster_Expecter) List(ctx interface{}, page interface{}, results interface{}) *MockPaster_List_Call {
	return &MockPaster_List_Call{Call: _e.mock.On("List", ctx, page, results)}
}

func (_c *MockPaster_List_Call) Run(run func(ctx context.Context, page int64, results int64)) *MockPaster_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockPaster_List_Call) Return(paste params.PasteListResult, err error) *MockPaster_List_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockPaster_List_Call) RunAndReturn(run func(context.Context, int64, int64) (params.PasteListResult, error)) *MockPaster_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListShares provides a mock function with given fields: ctx, pasteID
func (_m *MockPaster) ListShares(ctx context.Context, pasteID string) (params.PasteShareListResponse, error) {
	ret := _m.Called(ctx, pasteID)

	if len(ret) == 0 {
		panic("no return value specified for ListShares")
	}

	var r0 params.PasteShareListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (params.PasteShareListResponse, error)); ok {
		return rf(ctx, pasteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) params.PasteShareListResponse); ok {
		r0 = rf(ctx, pasteID)
	} else {
		r0 = ret.Get(0).(params.PasteShareListResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pasteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_ListShares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListShares'
type MockPaster_ListShares_Call struct {
	*mock.Call
}

// ListShares is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
func (_e *MockPaster_Expecter) ListShares(ctx interface{}, pasteID interface{}) *MockPaster_ListShares_Call {
	return &MockPaster_ListShares_Call{Call: _e.mock.On("ListShares", ctx, pasteID)}
}

func (_c *MockPaster_ListShares_Call) Run(run func(ctx context.Context, pasteID string)) *MockPaster_ListShares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaster_ListShares_Call) Return(_a0 params.PasteShareListResponse, _a1 error) *MockPaster_ListShares_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaster_ListShares_Call) RunAndReturn(run func(context.Context, string) (params.PasteShareListResponse, error)) *MockPaster_ListShares_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, page, results
func (_m *MockPaster) Search(ctx context.Context, query string, page int64, results int64) (params.PasteListResult, error) {
	ret := _m.Called(ctx, query, page, results)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 params.PasteListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) (params.PasteListResult, error)); ok {
		return rf(ctx, query, page, results)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) params.PasteListResult); ok {
		r0 = rf(ctx, query, page, results)
	} else {
		r0 = ret.Get(0).(params.PasteListResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, query, page, results)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockPaster_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - page int64
//   - results int64
func (_e *MockPaster_Expecter) Search(ctx interface{}, query interface{}, page interface{}, results interface{}) *MockPaster_Search_Call {
	return &MockPaster_Search_Call{Call: _e.mock.On("Search", ctx, query, page, results)}
}

func (_c *MockPaster_Search_Call) Run(run func(ctx context.Context, query string, page int64, results int64)) *MockPaster_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockPaster_Search_Call) Return(paste params.PasteListResult, err error) *MockPaster_Search_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockPaster_Search_Call) RunAndReturn(run func(context.Context, string, int64, int64) (params.PasteListResult, error)) *MockPaster_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrivacy provides a mock function with given fields: ctx, pasteID, public
func (_m *MockPaster) SetPrivacy(ctx context.Context, pasteID string, public bool) (params.Paste, error) {
	ret := _m.Called(ctx, pasteID, public)

	if len(ret) == 0 {
		panic("no return value specified for SetPrivacy")
	}

	var r0 params.Paste
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (params.Paste, error)); ok {
		return rf(ctx, pasteID, public)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) params.Paste); ok {
		r0 = rf(ctx, pasteID, public)
	} else {
		r0 = ret.Get(0).(params.Paste)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, pasteID, public)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_SetPrivacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrivacy'
type MockPaster_SetPrivacy_Call struct {
	*mock.Call
}

// SetPrivacy is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
//   - public bool
func (_e *MockPaster_Expecter) SetPrivacy(ctx interface{}, pasteID interface{}, public interface{}) *MockPaster_SetPrivacy_Call {
	return &MockPaster_SetPrivacy_Call{Call: _e.mock.On("SetPrivacy", ctx, pasteID, public)}
}

func (_c *MockPaster_SetPrivacy_Call) Run(run func(ctx context.Context, pasteID string, public bool)) *MockPaster_SetPrivacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockPaster_SetPrivacy_Call) Return(_a0 params.Paste, _a1 error) *MockPaster_SetPrivacy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaster_SetPrivacy_Call) RunAndReturn(run func(context.Context, string, bool) (params.Paste, error)) *MockPaster_SetPrivacy_Call {
	_c.Call.Return(run)
	return _c
}

// ShareWithUser provides a mock function with given fields: ctx, pasteID, userID
func (_m *MockPaster) ShareWithUser(ctx context.Context, pasteID string, userID string) (params.TeamMember, error) {
	ret := _m.Called(ctx, pasteID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ShareWithUser")
	}

	var r0 params.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (params.TeamMember, error)); ok {
		return rf(ctx, pasteID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) params.TeamMember); ok {
		r0 = rf(ctx, pasteID, userID)
	} else {
		r0 = ret.Get(0).(params.TeamMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, pasteID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaster_ShareWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareWithUser'
type MockPaster_ShareWithUser_Call struct {
	*mock.Call
}

// ShareWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
//   - userID string
func (_e *MockPaster_Expecter) ShareWithUser(ctx interface{}, pasteID interface{}, userID interface{}) *MockPaster_ShareWithUser_Call {
	return &MockPaster_ShareWithUser_Call{Call: _e.mock.On("ShareWithUser", ctx, pasteID, userID)}
}

func (_c *MockPaster_ShareWithUser_Call) Run(run func(ctx context.Context, pasteID string, userID string)) *MockPaster_ShareWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPaster_ShareWithUser_Call) Return(_a0 params.TeamMember, _a1 error) *MockPaster_ShareWithUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaster_ShareWithUser_Call) RunAndReturn(run func(context.Context, string, string) (params.TeamMember, error)) *MockPaster_ShareWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnshareWithUser provides a mock function with given fields: ctx, pasteID, userID
func (_m *MockPaster) UnshareWithUser(ctx context.Context, pasteID string, userID string) error {
	ret := _m.Called(ctx, pasteID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnshareWithUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, pasteID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaster_UnshareWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnshareWithUser'
type MockPaster_UnshareWithUser_Call struct {
	*mock.Call
}

// UnshareWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - pasteID string
//   - userID string
func (_e *MockPaster_Expecter) UnshareWithUser(ctx interface{}, pasteID interface{}, userID interface{}) *MockPaster_UnshareWithUser_Call {
	return &MockPaster_UnshareWithUser_Call{Call: _e.mock.On("UnshareWithUser", ctx, pasteID, userID)}
}

func (_c *MockPaster_UnshareWithUser_Call) Run(run func(ctx context.Context, pasteID string, userID string)) *MockPaster_UnshareWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPaster_UnshareWithUser_Call) Return(_a0 error) *MockPaster_UnshareWithUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaster_UnshareWithUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPaster_UnshareWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaster creates a new instance of MockPaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaster {
	mock := &MockPaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
